spring.application:
  name: todoList

spring:

  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
      SQL: debug
      orm:
        jdbc:
          bind: trace
        springframework: # 추가!
          security: debug # 추가!

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: LWJ6urV_sy1nbIVssW6P
            client-secret: gfZzSiKgO1
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/naver/callback
            scope:
              - name
              - email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

auth:
  jwt:
    issuer: team.sparta.com
    secret: PO4c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 168